### ISSUE TITLE
Remove soft delete of Media model

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-media#9]
- soft delete should be removed from the Media model
- Related file should be remove after removing the media entity

**Comment by ulin-evgeny** [comment]
Done.

**Comment by DenTray** [comment]
@ulin-evgeny not works for me, the delete API makrs media as soft deleted and file still presenting in my local storage

<img width="1354" alt="image" src="https://github.com/RonasIT/laravel-media/assets/9486872/696e6a8a-53e0-4a1a-9c17-a2ed4ed56432">

**Comment by ulin-evgeny** [comment]
Done.

**Comment by DenTray** [comment]
@ulin-evgeny works as expected now, thanks!
